2024-40-05 19:40:30->>>System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
Nombre de archivo: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   en System.Threading.Tasks.ValueTask`1.get_Result()
   en MySql.Data.MySqlClient.MySqlConnection.BeginTransaction()
   en tablaArbitro.Datos.DatosArbitro.agregarArbitro(Arbitro _arbitro) en C:\Users\sabri\OneDrive\Documentos\LAB Y PROY\TEORIA DE PROYECTO\tablaArbitro\tablaArbitro\Datos\DatosArbitro.cs:línea 104

=== Información de estado anterior al enlace ===
LOG: DisplayName = System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/sabri/OneDrive/Documentos/LAB Y PROY/TEORIA DE PROYECTO/tablaArbitro/tablaArbitro/bin/Debug/
LOG: PrivatePath inicial = NULL
Ensamblado de llamada : System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
===
LOG: Este enlace empieza en el contexto de carga default.
LOG: Utilización del archivo de configuración de la aplicación: C:\Users\sabri\OneDrive\Documentos\LAB Y PROY\TEORIA DE PROYECTO\tablaArbitro\tablaArbitro\bin\Debug\tablaArbitro.exe.Config
LOG: Utilizando el archivo de configuración de host: 
LOG: Utilizando el archivo de configuración del equipo en C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Referencia posterior a la directiva: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Ya se detectó el mismo enlace, que generó un error hr = 0x80070002.

2024-47-05 19:47:08->>>System.InvalidOperationException: The connection is already open.
   en MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   en MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   en MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en tablaArbitro.Datos.DatosArbitro.agregarArbitro(Arbitro _arbitro) en C:\Users\sabri\OneDrive\Documentos\LAB Y PROY\TEORIA DE PROYECTO\tablaArbitro\tablaArbitro\Datos\DatosArbitro.cs:línea 114
